config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  # get 'tasks/title', to: 'tasks#title', as: :title

  # get 'tasks/completed', to: 'tasks#completed'
  get '/tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'task/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action : only: [:show]

  def index
    @tasks = Task.all
  end

  def title
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <br>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <br>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul>
  <% @tasks.each do |task| %>
      <li style=list-style:none>
      <% if task.completed == true %>
      <%= check_box_tag 'task_id[]', task.id, {checked:true} %>
        <%= link_to task.title, task_path(task) %>
      <% else %>
        <%= check_box_tag 'task_id[]', task.id %>
        <%= link_to task.title, task_path(task) %>
      <% end %>

      </li>
  <% end %>
</ul>

<%= link_to 'Add a Task', tasks_new_path %>

app/views/tasks/new.html.erb
<h2>Adding a Task</h2>

<%= render 'form', task: @task %>

<%= link_to 'Back to index', tasks_path %>

app/views/tasks/show.html.erb
<%= link_to 'Back to index', tasks_path %>
<h1><%= @task.title %></h1>
<%= link_to 'Edit', edit_path(@task) %>
<%= link_to 'Delete', destroy_path, method: :delete, 'data-confirm': 'Are you sure?' %>
<p>
  <%= @task.details %>
</p>